// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgE3-TIRwxdKImO8_jlDuiivIw28o8tJo',
    appId: '1:110573212243:web:d5b92025f879f583f32ca6',
    messagingSenderId: '110573212243',
    projectId: 'todoapp-1b172',
    authDomain: 'todoapp-1b172.firebaseapp.com',
    storageBucket: 'todoapp-1b172.firebasestorage.app',
    measurementId: 'G-CCECJNFCSP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5PTqB4WXcQcbeqNbsrMAlrVd639IJHOE',
    appId: '1:110573212243:android:0d3d0e7faf96cc10f32ca6',
    messagingSenderId: '110573212243',
    projectId: 'todoapp-1b172',
    storageBucket: 'todoapp-1b172.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmCMZEL5olHgw4FWv0ZAwxUW4VcltDtTg',
    appId: '1:110573212243:ios:4fc15a05193ae8cdf32ca6',
    messagingSenderId: '110573212243',
    projectId: 'todoapp-1b172',
    storageBucket: 'todoapp-1b172.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmCMZEL5olHgw4FWv0ZAwxUW4VcltDtTg',
    appId: '1:110573212243:ios:4fc15a05193ae8cdf32ca6',
    messagingSenderId: '110573212243',
    projectId: 'todoapp-1b172',
    storageBucket: 'todoapp-1b172.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgE3-TIRwxdKImO8_jlDuiivIw28o8tJo',
    appId: '1:110573212243:web:1542171fa730f4a6f32ca6',
    messagingSenderId: '110573212243',
    projectId: 'todoapp-1b172',
    authDomain: 'todoapp-1b172.firebaseapp.com',
    storageBucket: 'todoapp-1b172.firebasestorage.app',
    measurementId: 'G-BD5VFZKCDY',
  );
}
